version: '3.9'
services:
  batquiz:
    container_name: batquiz
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: bat-mui-server:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      API_TOKEN: ${API_TOKEN}
      API_USER: ${API_USER}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - /var/www/batquiz/lib:/opt/app/lib
      - /var/www/batquiz/package.json:/opt/package.json
      - /var/www/batquiz/package-lock.json:/opt/package-lock.json
      - ./nginx-conf:/etc/nginx/conf.d

      - /var/www/batquiz/.env:/opt/app/.env
    ports:
      - '1337:3000'
    networks:
      - strapi

networks:
  strapi:
    name: ${DATABASE_NETWORK}
    external: true
